#!/bin/sh

pmount /dev/disk/by-label/Kindle kindle || exit 1

ebook-convert "$1" .mobi

# Get the name of the generated mobi file
BOOK_FILENAME="$(basename "${1%.*}.mobi")"

cp "$BOOK_FILENAME" /media/kindle/documents
rm "$BOOK_FILENAME"

pumount kindle

