#!/bin/bash

if [ $# == 0 ]; then
    echo "Provide a file descriptor (e.g. /dev/video0)"
    exit
fi

FD="$1"

function list_processes {
    echo $(lsof /dev/video0 | grep mem | cut -d' ' -f1 | xargs)
}

list_processes $FD

inotifywait -m $FD | while read event; do list_processes $FD; done

