#!/usr/bin/env bash
# Toggles layout between Colemak/Russian and QWERTY

layout_variant=`setxkbmap -query | awk '/variant/ { print $2 }'`

if [ "$layout_variant" = "colemak," ] ; then
	setxkbmap -layout us
else
	setxkbmap -layout us,ru -variant colemak,
fi
