#!/bin/sh
# Xdg-open a link or search from an argument or the dmenu prompt

DDG_URL="https://duckduckgo.com/html"
BROWSER_WINDOW_CLASS='Firefox'

# Read an input from an argument or the dmenu prompt
if [ ! -z "$1" ]; then
    input=$1
else
    input=`dmenu -p "Type a query: " </dev/null`
    if [ "$input" = "" ]; then
        exit 0;
    fi
fi

# Try to open
xdg-open "$input" 1>/dev/null 2>&1 || xdg-open "$DDG_URL/?q=$input"

